/*
 * internal OpenAPI
 *
 * This is the internal OpenAPI definition.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internalService

import (
	"context"
	"github.com/CHainGate/backend/internal/service"
	"github.com/CHainGate/backend/internalApi"
	"net/http"
)

// PaymentUpdateApiService is a service that implements the logic for the PaymentUpdateApiServicer
// This service should implement the business logic for every endpoint for the PaymentUpdateApi API.
// Include any external packages or services that will be required by this service.
type PaymentUpdateApiService struct {
	internalPaymentService service.IInternalPaymentService
}

// NewPaymentUpdateApiService creates a default api service
func NewPaymentUpdateApiService(internalPaymentService service.IInternalPaymentService) internalApi.PaymentUpdateApiServicer {
	return &PaymentUpdateApiService{internalPaymentService}
}

// UpdatePayment - update payment
func (s *PaymentUpdateApiService) UpdatePayment(_ context.Context, payment internalApi.PaymentUpdateDto) (internalApi.ImplResponse, error) {
	err := s.internalPaymentService.HandlePaymentUpdate(payment)
	if err != nil {
		return internalApi.Response(http.StatusInternalServerError, nil), err
	}

	return internalApi.Response(http.StatusOK, nil), nil
}
