/*
 * internal OpenAPI
 *
 * This is the internal OpenAPI definition.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package internalService

import (
	"CHainGate/backend/internalApi"
	"context"
	"errors"
	"net/http"
)

// PaymentUpdateApiService is a service that implements the logic for the PaymentUpdateApiServicer
// This service should implement the business logic for every endpoint for the PaymentUpdateApi API.
// Include any external packages or services that will be required by this service.
type PaymentUpdateApiService struct {
}

// NewPaymentUpdateApiService creates a default api service
func NewPaymentUpdateApiService() internalApi.PaymentUpdateApiServicer {
	return &PaymentUpdateApiService{}
}

// UpdatePayment - update payment
func (s *PaymentUpdateApiService) UpdatePayment(ctx context.Context, payment internalApi.Payment) (internalApi.ImplResponse, error) {
	// TODO - update UpdatePayment with the required logic for this service method.
	// Add api_payment_update_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return internalApi.Response(http.StatusNotImplemented, nil), errors.New("UpdatePayment method not implemented")
}
