openapi: 3.0.0
servers:
  - url: 'http://localhost:8000/api/internal'
info:
  description: >-
    This is the internal OpenAPI definition.
  version: 1.0.0
  title: internal OpenAPI
tags:
  - name: payment update
paths:
  /payment/webhook:
    put:
      tags:
        - payment update
      summary: update payment
      operationId: updatePayment
      responses:
        '200':
          description: payment updated
        '400':
          description: Bad Request
      requestBody:
        $ref: '#/components/requestBodies/PaymentUpdateDto'

components:
  requestBodies:
    PaymentUpdateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentUpdateDto'
  schemas:
    PaymentUpdateDto:
      title: Payment Update DTO
      type: object
      required:
        - paymentId
        - payAmount
        - payCurrency
        - actuallyPaid
        - paymentState
      properties:
        paymentId:
          type: string
          format: uuid
        payAmount:
          type: string
        payCurrency:
          type: string
          enum:
            - eth
            - btc
        actuallyPaid:
          type: string
        paymentState:
          type: string
          enum:
            - currency_selection
            - waiting
            - partially_paid
            - paid
            - confirmed
            - forwarded
            - finished
            - expired
            - failed