openapi: 3.0.0
servers:
  - url: 'http://localhost:8000/api/internal'
info:
  description: >-
    This is the internal OpenAPI definition.
  version: 1.0.0
  title: internal OpenAPI
tags:
  - name: payment update
paths:
  /payment/webhook:
    put:
      tags:
        - payment update
      summary: update payment
      operationId: updatePayment
      responses:
        '200':
          description: payment updated
        '400':
          description: Bad Request
      requestBody:
        $ref: '#/components/requestBodies/PaymentUpdateDto'

components:
  requestBodies:
    PaymentUpdateDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentUpdateDto'
  schemas:
    PaymentUpdateDto:
      title: Payment Update DTO
      type: object
      required:
        - payment_id
        - price_amount
        - price_currency
        - pay_amount
        - pay_currency
        - actually_paid
        - payment_status
      properties:
        payment_id:
          type: string
          format: uuid
        price_amount:
          type: number
          format: double
        price_currency:
          type: string
          enum:
            - usd
            - chf
        pay_amount:
          type: number
          format: double
        pay_currency:
          type: string
          enum:
            - eth
            - btc
        actually_paid:
          type: number
          format: double
          nullable: true
        payment_status:
          type: string
          enum:
            - waiting
            - partially_paid
            - paid
            - sending
            - finished
            - expired
            - failed
