openapi: 3.0.0
servers:
  - url: 'http://localhost:8000/api/public'
info:
  description: >-
    This is the public OpenAPI definition.
  version: 1.0.0
  title: Public OpenAPI
tags:
  - name: payment
paths:
  /payment:
    post:
      tags:
        - payment
      summary: Create a new payment with currency already defined
      description: 'Create a new payment with currency already defined. Returns only a payment address'
      operationId: newPayment
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
      responses:
        '201':
          description: payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponseDto'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      requestBody:
        $ref: '#/components/requestBodies/Payment'
  /invoice:
    post:
      tags:
        - invoice
      summary: Create a new invoice
      description: 'Create a new invoice. Returns an URL'
      operationId: newInvoice
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
      responses:
        '201':
          description: invoice created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponseDto'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      requestBody:
        $ref: '#/components/requestBodies/Invoice'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  requestBodies:
    Payment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRequestDto'
    Invoice:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InvoiceRequestDto'
  schemas:
    PaymentResponseDto:
      title: Payment Response DTO
      type: object
      required:
        - id
        - payAddress
        - priceCurrency
        - payAmount
        - payCurrency
        - actuallyPaid
        - callbackUrl
        - paymentState
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        payAddress:
          type: string
        priceAmount:
          type: number
          format: double
        priceCurrency:
          type: string
          enum:
            - usd
            - chf
        payAmount:
          type: string
        payCurrency:
          type: string
          enum:
            - eth
            - btc
        actuallypaid:
          type: string
        callbackUrl:
          type: string
        paymentState:
          type: string
          enum:
            - currency_selection
            - waiting
            - partially_paid
            - paid
            - confirmed
            - forwarded
            - finished
            - expired
            - failed
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PaymentRequestDto:
      title: Payment Request DTO
      type: object
      required:
        - priceCurrency
        - priceAmount
        - payCurrency
        - callbackUrl
      properties:
        priceCurrency:
          type: string
          enum:
            - usd
            - chf
        priceAmount:
          type: number
          format: double
        payCurrency:
          type: string
          enum:
            - eth
            - btc
        callbackUrl:
          type: string
    InvoiceResponseDto:
      title: Invoice Response DTO
      type: object
      required:
        - id
        - payAddress
        - priceCurrency
        - payAmount
        - payCurrency
        - actuallyPaid
        - callbackUrl
        - paymentState
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        payAddress:
          type: string
        priceAmount:
          type: number
          format: double
        priceCurrency:
          type: string
          enum:
            - usd
            - chf
        actuallyPaid:
          type: string
        callbackUrl:
          type: string
        invoiceUrl:
          type: string
        paymentState:
          type: string
          enum:
            - currency_selection
            - waiting
            - partially_paid
            - paid
            - confirmed
            - forwarded
            - finished
            - expired
            - failed
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    InvoiceRequestDto:
      title: Invoice Request DTO
      type: object
      required:
        - priceCurrency
        - priceAmount
        - callbackUrl
      properties:
        priceCurrency:
          type: string
          enum:
            - usd
            - chf
        priceAmount:
          type: number
          format: double
        callbackUrl:
          type: string