openapi: 3.0.0
servers:
  - url: 'http://localhost/api/public'
info:
  description: >-
    This is the public OpenAPI definition.
  version: 1.0.0
  title: Public OpenAPI
tags:
  - name: payment
paths:
  /payment:
    post:
      tags:
        - payment
      summary: Create a new payment
      description: 'Create a new payment'
      operationId: newPayment
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
      responses:
        '201':
          description: payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      requestBody:
        $ref: '#/components/requestBodies/Payment'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  requestBodies:
    Payment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRequest'
  schemas:
    Payment:
      title: Payment
      type: object
      properties:
          id:
           type: string
           format: uuid
          pay_address:
           type: string
          price_amount:
           type: number
          price_currency:
           type: string
           enum:
             - usd
             - chf
          pay_amount:
           type: number
          pay_currency:
           type: string
           enum:
             - eth
             - btc
          actually_paid:
           type: number
          callback_url:
           type: string
          payment_status:
           type: string
           enum:
             - waiting
             - partially_paid 
             - paid
             - sending
             - finished
             - expired
             - failed
          created_at:
           type: string
           format: date-time
          updated_at:
           type: string
           format: date-time
    PaymentRequest:
      title: Payment Request
      type: object
      properties:
        price_currency:
          type: string
          enum:
            - usd
            - chf
        price_amount:
          type: number
        pay_currency:
          type: string
          enum:
            - eth
            - btc
        callback_url:
          type: string