name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18


    - name: generate config openApi server code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/swaggerui/config/openapi.yaml -g go-server -o /local/ --additional-properties=sourceFolder=configApi,packageName=configApi
    - name: generate public openApi server code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/swaggerui/public/openapi.yaml -g go-server -o /local/ --additional-properties=sourceFolder=publicApi,packageName=publicApi
    - name: generate internal openApi server code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/swaggerui/internal/openapi.yaml -g go-server -o /local/ --additional-properties=sourceFolder=internalApi,packageName=internalApi
    - name: generate proxy openApi client code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/CHainGate/proxy-service/main/swaggerui/openapi.yaml -g go -o /local/proxyClientApi --ignore-file-override=/local/.openapi-generator-ignore --additional-properties=sourceFolder=proxyClientApi,packageName=proxyClientApi
    - name: generate eth openApi client code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/CHainGate/ethereum-service/main/swaggerui/openapi.yaml -g go -o /local/ethClientApi --ignore-file-override=/local/.openapi-generator-ignore --additional-properties=sourceFolder=ethClientApi,packageName=ethClientApi
    - name: generate btc openApi client code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://raw.githubusercontent.com/CHainGate/bitcoin-service/main/swaggerui/openapi.yaml -g go -o /local/btcClientApi --ignore-file-override=/local/.openapi-generator-ignore --additional-properties=sourceFolder=btcClientApi,packageName=btcClientApi
    - name: install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - name: change permissions
      run: sudo chown -R $USER:$USER ${{ github.workspace }}
    - name: run goimports
      run: goimports -w .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: Run coverage
      run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
