name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: generate config openApi code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/openApiSpecifications/config.yaml -g go-server -o /local/ --additional-properties=sourceFolder=configApi,packageName=configApi
    - name: generate public openApi code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/openApiSpecifications/public.yaml -g go-server -o /local/ --additional-properties=sourceFolder=publicApi,packageName=publicApi
    - name: generate internal openApi code
      run: docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/openApiSpecifications/internal.yaml -g go-server -o /local/ --additional-properties=sourceFolder=internalApi,packageName=internalApi
    - name: install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest
    - name: run goimports
      run: sudo goimports -w .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
